openapi: 3.0.0
info:
  title: Coronatime API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://127.0.0.1:8000/api
    description: local server
  # - url: http://producation.app/api
  #   description: production server

paths:
  /register:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1register"
# paths:
#   /users:
#     get:
#       summary: Returns a list of users.
#       responses:
#         "200":
#           description: A JSON array of user names
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   type: string
