openapi: 3.0.0
info:
  title: Movie quotes API
  description: This is the backend API for the Movie Quotes application.
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: https://movie-quotes-back.elene-javakhishvili.redberryinternship.ge/api
    description: production server

paths:
  /register:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1register"
  /login:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1login"
  /logout:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1logout"
  /user:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1user"
  /user/{id}:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1user~1{id}"    
  /forgot-password:
    $ref: "./_swagger/paths/password.yaml#/paths/~1forgot-password"
  /reset-password:
    $ref: "./_swagger/paths/password.yaml#/paths/~1reset-password"
  /movie:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1movie"
  /movies:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1movies"
  /movie/{id}:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1movie~1{id}"
  /quote:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote"
  /quotes:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quotes"
  /quote/{id}:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote~1{id}"
  /genres:
    $ref: "./_swagger/paths/genres.yaml#/paths/~1genres"
  /quotes/{id}/comments:
    $ref: "./_swagger/paths/comments.yaml#/paths/~1quotes~1{id}~1comments"
  /quotes/{id}/likes:
    $ref: "./_swagger/paths/likes.yaml#/paths/~1quotes~1{id}~1likes"
  /notifications:
    $ref: "./_swagger/paths/notification.yaml#/paths/~1notifications"
  /notification/{id}:
    $ref: "./_swagger/paths/notification.yaml#/paths/~1notification~1{id}"
  /notifications/read-all:
    $ref: "./_swagger/paths/notification.yaml#/paths/~1notifications~1read-all"
  /notification/{id}/read:
    $ref: "./_swagger/paths/notification.yaml#/paths/~1notification~1{id}~1read"
components:
  securitySchemes:
    sanctumAuth:
      type: apiKey
      in: cookie
      name: X-XSRF-TOKEN
    laravelSession:
      type: apiKey
      in: cookie
      name: laravel_session
  schemas:
    User:
      allOf:
        - $ref: "./_swagger/schemas/user.yaml#/components/schemas/User"
    Movie:
      allOf:
        - $ref: "./_swagger/schemas/dbMovie.yaml#/components/schemas/Movie"
    Quote:
      allOf:
        - $ref: "./_swagger/schemas/dbQuote.yaml#/components/schemas/Quote"
    Like:
      allOf:
        - $ref: "./_swagger/schemas/dbLike.yaml#/components/schemas/Like"
    Comment:
      allOf:
        - $ref: "./_swagger/schemas/dbComment.yaml#/components/schemas/Comment"
    Notification:
      allOf:
        - $ref: "./_swagger/schemas/dbNotification.yaml#/components/schemas/Notification"
    Genre:
      allOf:
        - $ref: "./_swagger/schemas/dbGenre.yaml#/components/schemas/Genre"
