openapi: 3.0.0
info:
  title: Movie quotes API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  # - url: http://producation.app/api
  #   description: production server

paths:
  /register:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1register"
  /login:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1login"
  /user:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1user"
  /verify/{id}/{hash}:
    $ref: "./_swagger/paths/email.yaml#/paths/~1verify"
  /movie:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1movie"
  /movies:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1movies"
  /movie/{id}:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1movie~1{id}"
components:
  securitySchemes:
    sanctumAuth:
      type: apiKey
      in: cookie
      name: X-CSRF-TOKEN
    # schemas:
    #   Movie:
    #     allOf:
    #       - $ref: "./_swagger/schemas/movie.yaml#/components/schemas/Movie" 